<?php

declare(strict_types=1);

namespace App\Scanning\Preflight;

use App\Scanning\Enums\SkipReason;
use App\Scanning\Support\PathMatcher;

/**
 * Detects generated and minified files by name pattern and by content.
 */
final class GeneratedFileDetector
{
    private const MARKERS = [
        '@generated',
        'do not edit',
        'auto-generated',
        'autogenerated',
        'automatically generated',
        'generated by',
        'this file is generated',
        'code generated',
    ];

    private const MINIFIABLE_EXTENSIONS = ['js', 'mjs', 'cjs', 'css', 'json', 'map', 'svg'];

    /**
     * @param  list<string>  $patterns  Basename globs from config.
     */
    public static function detect(string $relativePath, string $absolutePath, int $size, array $patterns): ?SkipReason
    {
        $basename = basename($relativePath);

        foreach ($patterns as $pattern) {
            if (PathMatcher::matchesGlob($basename, $pattern)) {
                return str_contains(strtolower($pattern), '.min.') ? SkipReason::Minified : SkipReason::Generated;
            }
        }

        if ($size === 0) {
            return null;
        }

        $handle = fopen($absolutePath, 'rb');
        if ($handle === false) {
            return null;
        }
        $head = (string) fread($handle, 2048);
        fclose($handle);

        return self::detectFromContent($basename, $size, $head);
    }

    public static function detectFromContent(string $basename, int $size, string $head): ?SkipReason
    {
        $firstLines = strtolower(implode("\n", array_slice(explode("\n", $head), 0, 5)));
        foreach (self::MARKERS as $marker) {
            if (str_contains($firstLines, $marker)) {
                return SkipReason::Generated;
            }
        }

        $extension = strtolower(pathinfo($basename, PATHINFO_EXTENSION));
        if ($size > 1024 && in_array($extension, self::MINIFIABLE_EXTENSIONS, true)) {
            $lines = substr_count($head, "\n") + 1;
            if (strlen($head) / $lines > 300) {
                return SkipReason::Minified;
            }
        }

        return null;
    }
}
