---
description: {{ $repository }} conventions generated by Sentinel Slop
globs:
alwaysApply: true
---

# {{ $repository }} conventions

{!! $rules['summary'] !!}

Stack: {{ $stack->describeFrameworks() ?: ($stack->primaryLanguage() ?? 'unknown') }}{{ $stack->describeRuntimes() !== '' ? ' on '.$stack->describeRuntimes() : '' }}. Generated from Sentinel Slop's {{ implode(', ', $rulesets) }} rulesets, which are not files in this repository.

@foreach ($rules['sections'] as $section)
## {{ $section['heading'] }}

@foreach ($section['items'] as $item)
- {!! $item !!}
@endforeach

@endforeach
## Working agreement

- Run the full test suite before and after every change; never leave it failing.
- Fix the cause of a lint or static-analysis error rather than adding a suppression comment.
- Keep changes scoped to the task; note unrelated problems instead of fixing them in passing.
