---
description: {{ $repository }} conventions generated by Sentinel Slop
globs:
alwaysApply: true
---

# {{ $repository }} conventions

{!! $rules['summary'] !!}

Stack: {{ implode(', ', $stack->frameworks) ?: ($stack->primaryLanguage() ?? 'unknown') }}. Rulesets applied: {{ implode(', ', $rulesets) }}.

@foreach ($rules['sections'] as $section)
## {{ $section['heading'] }}

@foreach ($section['items'] as $item)
- {!! $item !!}
@endforeach

@endforeach
## Working agreement

- Run the full test suite before and after every change; never leave it failing.
- Fix the cause of a lint or static-analysis error rather than adding a suppression comment.
- Keep changes scoped to the task; note unrelated problems instead of fixing them in passing.
